// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeek8.EF;

namespace TestWeek8.EF.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20211029100957_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeek8.Core.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cenone di Capodanno"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pranzo di Natale"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pranzo domenicale"
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Plate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlateType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Plates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sugo, macinato, cipolla, parmigiano, orecchiette fresche",
                            MenuId = 1,
                            Name = "Orecchiette con polpette",
                            PlateType = 0,
                            Price = 10.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Polpettone, brodo e carote",
                            MenuId = 1,
                            Name = "Polpettone con carote",
                            PlateType = 1,
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Biscotti, panna, ricotta, nutella",
                            MenuId = 1,
                            Name = "Cheesecake alla nutella",
                            PlateType = 3,
                            Price = 5.50m
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mrossi@abc.it",
                            Password = "1234",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "michi13@abc.it",
                            Password = "5678",
                            Role = 1
                        });
                });

            modelBuilder.Entity("TestWeek8.Core.Models.Plate", b =>
                {
                    b.HasOne("TestWeek8.Core.Models.Menu", "Menu")
                        .WithMany("Plates")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
